#!/bin/bash
set -eu
source "$(dirname "$0")/_wickshield_env.sh"

HOUR=$(date +%H 2>/dev/null || echo 12)
if [ "$HOUR" -ge 1 ] && [ "$HOUR" -le 6 ]; then
  WORKERS=4
elif [ "$HOUR" -ge 9 ] && [ "$HOUR" -le 17 ]; then
  WORKERS=8
else
  WORKERS=6
fi

export WICKSHIELD_MONITOR_WORKERS="${WICKSHIELD_MONITOR_WORKERS:-$WORKERS}"
export WICKSHIELD_OHLCV_WORKERS="${WICKSHIELD_OHLCV_WORKERS:-$WORKERS}"
export WICKSHIELD_MONITOR_DAYS_BACK="${WICKSHIELD_MONITOR_DAYS_BACK:-0.3}"
export WICKSHIELD_MONITOR_LIGHT="${WICKSHIELD_MONITOR_LIGHT:-1}"
export WICKSHIELD_REQUEST_TIMEOUT="${WICKSHIELD_REQUEST_TIMEOUT:-3}"
export WICKSHIELD_SKIP_TIMEOUT="${WICKSHIELD_SKIP_TIMEOUT:-1}"
export WICKSHIELD_CIRCUIT_BREAKER="${WICKSHIELD_CIRCUIT_BREAKER:-1}"
export WICKSHIELD_RATE_LIMIT_ENABLE="${WICKSHIELD_RATE_LIMIT_ENABLE:-1}"
export WICKSHIELD_CLAIM_FULL_VERIFY="${WICKSHIELD_CLAIM_FULL_VERIFY:-1}"
export WICKSHIELD_CACHE_TTL="${WICKSHIELD_CACHE_TTL:-30}"

exec bash "$ROOT/scripts/run_wickshield_monitor.sh"
