#!/bin/bash
set -eu
source "$(dirname "$0")/_wickshield_env.sh"
export WICKSHIELD_POOL="${WICKSHIELD_POOL:-50000}"
export WICKSHIELD_COVERAGE="${WICKSHIELD_COVERAGE:-100000}"
export WICKSHIELD_MONITOR_DAYS_BACK="${WICKSHIELD_MONITOR_DAYS_BACK:-0.3}"
export WICKSHIELD_MONITOR_LIGHT="${WICKSHIELD_MONITOR_LIGHT:-1}"
export WICKSHIELD_REQUEST_TIMEOUT="${WICKSHIELD_REQUEST_TIMEOUT:-3}"
export WICKSHIELD_SKIP_TIMEOUT="${WICKSHIELD_SKIP_TIMEOUT:-1}"
export WICKSHIELD_CIRCUIT_BREAKER="${WICKSHIELD_CIRCUIT_BREAKER:-1}"
export WICKSHIELD_RATE_LIMIT_ENABLE="${WICKSHIELD_RATE_LIMIT_ENABLE:-1}"
export WICKSHIELD_CLAIM_FULL_VERIFY="${WICKSHIELD_CLAIM_FULL_VERIFY:-1}"
export WICKSHIELD_CACHE_TTL="${WICKSHIELD_CACHE_TTL:-30}"
export WICKSHIELD_OHLCV_WORKERS="${WICKSHIELD_OHLCV_WORKERS:-}"
export WICKSHIELD_MONITOR_WORKERS="${WICKSHIELD_MONITOR_WORKERS:-}"
mkdir -p data/logs data/wickshield
_wickshield_cli monitor
